task_name: 'mfd-autoencoder'
task_phase: 1

# Model
top_k: 5

# Seed
seed: 42
deterministic: False

# Paths
checkpoint_path: 'logging/{uuid}/checkpoint/'
images_path: 'logging/{uuid}/images/'
logging_path: 'logging/{uuid}/logging/'
pretrain_path: 'logging/pretrain/'
tensorboard_path: 'logging/tensorboard/{uuid}/'

# Checkpoints
checkpoint_encoder: 'checkpoint-encoder.pth.tar'
checkpoint_decoder: 'checkpoint-decoder.pth.tar'
checkpoint_optm: 'checkpoint-optm-phase-1.pth.tar'

# Dataset
dataset_worker_num: 6

dataset_train_path: '/files/ComputeData/ILSVRC2012/ILSVRC2012_image_train_lmdb/'
dataset_valid_path: '/files/ComputeData/ILSVRC2012/ILSVRC2012_image_valid_lmdb/'

# Training
epochs: 10
learning_rate: 1e-5
momentum: 0.9
weight_decay: 1e-4

cudnn_benchmark: True

batch_size: 32

# Logging
logging_interval: 50
heavy_logging_interval: 100
valid_images_save_num: 20
