task_name: 'mfd-attention'
task_phase: 2

# Model
top_k: 5

# Seed
seed: 42
deterministic: False

# Paths
checkpoint_path: 'logging/{uuid}/checkpoint/'
images_path: 'logging/{uuid}/images/'
logging_path: 'logging/{uuid}/logging/'
pretrain_path: 'logging/pretrain/'
tensorboard_path: 'logging/tensorboard/{uuid}/'

# Checkpoints
checkpoint_encoder: 'checkpoint-encoder.pth.tar'
checkpoint_decoder: 'checkpoint-decoder.pth.tar'
checkpoint_resnet: 'resnet18-5c106cde.pth'
checkpoint_attentioner: 'checkpoint-attentioner.pth.tar'
checkpoint_optm: 'checkpoint-optm-phase-2.pth.tar'

# Dataset
dataset_worker_num: 6

dataset_train_path: '/files/ComputeData/ILSVRC2012/ILSVRC2012_image_train_lmdb/'
dataset_valid_path: '/files/ComputeData/ILSVRC2012/ILSVRC2012_image_valid_lmdb/'

# Training
epochs: 5
learning_rate: 0.01

cudnn_benchmark: True

batch_size: 32

# Training Logging
logging_interval: 100
heavy_logging_interval: 100

# Validation Logging
valid_images_save_num: 20
